apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: examiner
  namespace: apps
spec:
  image: quay.io/heubeck/examiner
  interval: "10m0s"
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: examiner
  namespace: apps
spec:
  imageRepositoryRef:
    name: examiner
  policy:
    semver:
      range: ${examiner_version}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: examiner
  namespace: apps
spec:
  interval: 1m
  url: oci://quay.io/heubeck/timoni-instances/examiner
  ref:
    tag: non-prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: examiner
  namespace: apps
spec:
  targetNamespace: apps
  interval: 1m
  retryInterval: 30s
  timeout: 1m
  path: ./
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: examiner
  images:
    - name: quay.io/heubeck/examiner
      newTag: 1.11.4 # {"$imagepolicy": "apps:examiner:tag"}
  postBuild:
    substitute:
      echo_message: "\U0001F3A2 CloudLand 2023 R0ckX \U0001F3B8"
